Dev refactor 16 спринт
OlegQt/Yandex-Practicum_PlaylistMaker pull request #10
Opened 2023-07-02 15:42 UTC by OlegQt

2023-07-08 18:53 UTC, OlegQt commented
Реализацию логики работы MediaPlayer вынес в отдельный класс MusicPlayerControllerImpl наследующий интерфейс
из DOMAIN слоя. Далее уже ViewModel активити плеера использует этот класс.

2023-07-09 13:34 UTC, i-masloed commented on app/src/main/java/com/playlistmaker/presentation/ui/viewmodel/ActivitySearchVm.kt
> +        val musRequest = MusicSearchRequest(songName)
Эти 3 переменные -это объекты дата -слоя, и поэтому не должны использоваться и создаваться в UI-слое. На данный момент можно вынести их создание в соответствующий им слой. В следующих спринтах тема с созданием зависимостей и di будет разбираться подробно. Сейчас самое важное, что следует помнить, это то, что вьюмодель может зависеть только от интерфейса  интерактора или юзкейса.

2023-07-09 13:34 UTC, i-masloed commented on app/src/main/java/com/playlistmaker/presentation/ui/viewmodel/ActivitySearchVm.kt
> +        searchScreenState.postValue(ActivitySearchState.InitialState(null))
Рекомендация: тк этот код гарантировано выполняется в UI -потоке, то можно использовать просто value, а не postValue

2023-07-09 13:34 UTC, i-masloed commented on app/src/main/java/com/playlistmaker/presentation/ui/viewmodel/ActivitySearchVm.kt
> +            when (result.errorCode) {
errorCode - это код ответа сервера, то есть то, что относится к дата-слою, не стоит выносить проверку кода сервера на UI-слой, лучше сделать domain-модель, в которой будет содержаться информация, успешным был запрос или нет.

2023-07-09 13:34 UTC, i-masloed commented on app/src/main/java/com/playlistmaker/presentation/ui/viewmodel/ActivitySearchVm.kt
> +            Toast.makeText(
Тост - это отрисовка UI, она должна быть в активити или фрагменте

2023-07-09 13:34 UTC, i-masloed commented on app/src/main/java/com/playlistmaker/presentation/ui/activities/ActivitySearch.kt
> +        if (flag) {
Рекомендация: в коде нет использования этого метода( да и соответствующей ему лайвдаты) со значением False. В лайв дате можно указать тип Unit. А вобще для событий, не требующих сохранения состояния, лучше использовать SingleLiveEvent

2023-07-09 13:34 UTC, i-masloed commented on app/src/main/java/com/playlistmaker/presentation/ui/activities/ActivitySearch.kt
> +            finish()
Рекомендация: Знаю, что это тема не этого спринта, но хочу обратить внимание на такую важную штуку как стек активити. Сейчас , как я вижу, каждый раз при старте нового экрана в предыдущем вызывается finish(). При этом при обработке нажатия назад также создается новый экран и завершается текущий. Это неверно с точки зрения формирования стека. Должно быть так: при старте нового экрана мы не завершаем текущий , а просто стартуем новый. При возврате назад мы только завершаем текущий и у нас становится активным верхний экран стека приложения, те предыдущий. Рекомендую здесь, если тема непонятна, обратиться к наставнику. Это штука достаточно важна в реальной разработке

2023-07-09 13:34 UTC, i-masloed commented on app/src/main/java/com/playlistmaker/presentation/ui/activities/ActivitySearch.kt
> +        binding.clsSearch.visibility = when (visibility) {
Рекомендация: в  котлин есть удобный экстеншн -метод `isVisible`, принимает boolean

2023-07-09 13:34 UTC, i-masloed commented on app/src/main/java/com/playlistmaker/presentation/ui/activities/ActivitySearch.kt
> +        outState.putString("searchTxt", binding.txtSearch.text.toString())
Рекомендация: ключ для сохранения лучше вынести в константы

2023-07-09 13:34 UTC, i-masloed commented on app/src/main/java/com/playlistmaker/presentation/ui/activities/ActivitySearch.kt
> +        App.instance.saveCurrentScreen(Screen.MAIN)
Рекомендация: здесь при правильном подходе(комментарий о стеке активити оставила выше) нет необходимости в переопределении этого метода

2023-07-09 13:34 UTC, i-masloed commented on app/src/main/java/com/playlistmaker/util/Resource.kt
> +    class Error<T>(errorCode: Int):Resource<T>(null,errorCode)
здесь лучше использовать не код веб-ответа, а  enum класс, который будет принадлежать доменному слою

2023-07-09 13:34 UTC, i-masloed commented on app/src/main/java/com/playlistmaker/presentation/ui/activities/ActivitySettings.kt
> +        App.instance.saveCurrentScreen(Screen.SETTINGS)
Рекомендация: при правильно организованном стеке приложения в таких вызовах нет необходимости

2023-07-09 13:42 UTC, OlegQt commented on app/src/main/java/com/playlistmaker/presentation/ui/viewmodel/ActivitySearchVm.kt
> +        val musRequest = MusicSearchRequest(songName)
И куда их выносить? В domain слое их быть не должно, в UI слое тоже. Но не же как то надо создать эти классы?

2023-07-11 16:22 UTC, OlegQt commented
Исправления:

1. Добавлен класс креатор (singleton)
2. Все startActivity(intent) перенесены внутрь Activity и вызываются посредством изменения SingleLiveEvent<Screen> в ViewModel
3. Отображение тостов заменено отображением AllertDialog, вызвыается внутри activity, через observer соответсвующей LifeData внутри viewModel.
4. Во всех активити убраны зависимости от Data - слоя
5. Обработка ошибок сервера перенесена в MusicRepositoryImpl Data-layer с добавлением соответствующего класса модели-ошибок (ErrorList)
6. MusicPlayerImpl перенесен в Data-слой
7. Для функции startPlayerActivity создана соответствующая lifeData типа SingleLiveEvent<MusTrack>
8. При нажатии на recyclerView происходит передача инф из recucler.data -> lifeData, затем запуск startPlayerActivity()
9. Убрал ошибку закрытия текущего экрана при старте другой activity
10. Запуск intent из ActivitySettingsVM перенесен внутрь Activity (создавать специальную lifedata не стал, т.к в данном случае вызов intent происходит напрямую по нажатию соответствующей кнопки и удлинять путь вызова через vieModel наверное нет смысла)
11. Вся работа с sharedPrefs вынесена в Data-layer

2023-07-12 15:04 UTC, NoDopezzz requested changes

2023-07-12 15:04 UTC, kirillNay commented on app/src/main/java/com/playlistmaker/data/playerimpl/MusicPlayerControllerImpl.kt
> +        } catch (e: IllegalStateException) {
⏫ Чтобы не выставлять `catch` под каждую ошибку (учитывая то, что мы их игнорируем и не орбабатываем), мы можем просто ловить `Throwable`. `Throwable` является интерфейсом, который реализуют все выкидываемые исключения, поэтому мы можем гарантировать, что все наши ошибку будут словлены

2023-07-12 15:04 UTC, kirillNay commented on app/src/main/java/com/playlistmaker/data/network/RetrofitNetworkClient.kt
> +    override fun doRequest(dto: Any): MusicResponse {
⏫ `NetworkClient` - интерфейс, который описывает работу клиента сети. Его метод `doRequest` на вход он принимает какой-то `Request` и возвращает какой-то `Response`. Если мы хотим максимально обобщить этот интерфейс, то мы можем типы `Request` и `Response` сделать дженериками. И тогда интерфейс будет выглядеть следующим образом
```
interface NetworkClient<TRequest, TResponse> {
     fun doRequest(request: TRequest): TResponse
}
```

Лучше стараться не использовать Any для передачи аргументов или получении результата, иначе мы можем столкнуться с неконтролируемыми кастами классов, которые в теории могут вызывать ошибки. Так мы понижаем стабильности и качество кода

2023-07-12 15:04 UTC, kirillNay commented on app/src/main/java/com/playlistmaker/data/repository/MusicRepositoryImpl.kt
> +                // Цикл ниже преобразует все данные в данные модели слоя DATA
Наверно, имелось в виду "в данные модели domain")

2023-07-12 15:04 UTC, kirillNay commented on app/src/main/java/com/playlistmaker/data/repository/MusicRepositoryImpl.kt
> +            else -> Resource.Error(ErrorList.UNKNOWN_ERROR)
⏫ `Resource` - кажется, что не очень подходящее имя для класса. Здесь `Result` будет описывать его лучше

2023-07-12 15:04 UTC, kirillNay commented on app/src/main/java/com/playlistmaker/data/repository/MusicTrackRepositoryImpl.kt
> +    private val sharedPreferences = context.getSharedPreferences(PREFERENCES, Context.MODE_PRIVATE)
⏫ `SharedPreference` используются в нескольких репозиториях. Может мы его инициализацю можем убрать в `Creator`, а в репозитории передавать сразу `sharedPreferences`?

2023-07-12 15:04 UTC, kirillNay commented on app/src/main/java/com/playlistmaker/presentation/ui/activities/ActivityPlayer.kt
> +        vm.getCurrentMusTrack.observe(this) {
👍 Очень хорошая реализация MVVM подхода!

2023-07-12 15:04 UTC, kirillNay commented on app/src/main/java/com/playlistmaker/presentation/ui/activities/ActivityPlayer.kt
> +    override fun onCreate(savedInstanceState: Bundle?) {
⏫ Для поддержания удобочитаемости советую строить методы в классе в следующем порядке:
 `override public -> public -> override  protected -> protected -> override private -> private`

2023-07-12 15:04 UTC, kirillNay commented on app/src/main/java/com/playlistmaker/presentation/ui/viewmodel/ActivitySearchVm.kt
> +        if (res != -1) {
⏫ Лучше всю эту логику вынести в репозиторий

2023-07-12 15:04 UTC, kirillNay commented on app/src/main/java/com/playlistmaker/presentation/ui/viewmodel/ActivitySearchVm.kt
> +    private val musRepo by lazy { Creator.getCreator().getMusicRepository(application) }
⚠️ Мы не должны обращаться `data` слою напрямую через `Repository`. Все обращение должно проходить через `domain` слой, через классы `UseCase` или `Interactor`. Возможно сейчас такое проксирование запросов кажется лишним, но при росте проекта правильное разделение логики между слоями положительно отразится на поддержке этого проекта

2023-07-12 15:04 UTC, kirillNay commented on app/src/main/java/com/playlistmaker/presentation/ui/viewmodel/PlayerVm.kt
> +    private val musTrackRepo = Creator.getCreator().getMusicTrackRepository(externalContext = application.baseContext)
⚠️ Обрати внимание, что тут также мы не должно обращаться к репозиторию напрямую, только через `domain`

2023-07-12 15:04 UTC, NoDopezzz commented on app/src/main/java/com/playlistmaker/util/Creator.kt
> +    fun createMusicSearchRequest(strRequest:String):MusicSearchRequest{
⚠️ Обрати внимание, что `Creator` не должен возращать `Impl` классы, он должен возвращать интерфейсы. Так как класс, который запрашивает у Creator'а репозиторий находится в слое domain, то ему знакомы только интерфейсы и ничего о реализации.
В данном случае все, что тебе стоит исправить, это убрать Impl для get* методов. Например, 
```
fun getMusicRepository(externalContext: Context): MusicRepository {
        return MusicRepositoryImpl(networkClient = RetrofitNetworkClient(), context = externalContext)
    }
```

Это очень важная часть принципа инверсии зависимостей.

2023-07-13 17:03 UTC, OlegQt commented on app/src/main/java/com/playlistmaker/presentation/ui/viewmodel/ActivitySearchVm.kt
> +        if (res != -1) {
Каким образом, если musicSearchHistoryList это локальная переменная, в которой хранится загруженная история треков. Вы предлагаете сделать дополнительную функцию внутри репозитория? Тогда каждый раз придется дополнительно обращаться внутри к SharedPrefs  и вытаскивать оттуда список, потом менять его и снова сохранять?

2023-07-14 18:03 UTC, NoDopezzz commented on app/src/main/java/com/playlistmaker/presentation/ui/viewmodel/ActivitySearchVm.kt
> +        if (res != -1) {
Я скорее имел в виду, что можно вынести проверку на максимальное количество треков в истории в data слой. Сама реализация может и измениться

2023-07-15 16:04 UTC, merged